const KEY='practice-app-data-v1';
const DEFAULT_TEMPOS=[40,42,44,46,48,50,52,54,56,58,60,63,66,69,72,76,80,84,88,92,96,100,104,108,112,116,120,126,132,138,144,152,160,168,176,184,192,200,208,216,224];
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const now=()=>Date.now();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let data=load(); let route={name:'home',args:{}}; let practiceState=null; let audio=null; let modal=null;
function load(){try{const d=JSON.parse(localStorage.getItem(KEY));if(d)return d}catch{}return {activities:[],items:[],targets:[],recent:[],settings:{defaultScoring:'streak',defaultProgression:'traditional',defaultGoal:5,metronome:true,timeSignature:'none'}}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function go(name,args={}){route={name,args};modal=null;render();window.scrollTo(0,0)}
function appShell(content,back=null){return `<div class="app"><div class="topbar"><div class="brand">Practice App</div>${back?`<button class="icon-btn" onclick="go('${back.name}',${JSON.stringify(back.args||{})})" aria-label="Back">‹</button>`:`<div></div>`}</div>${content}</div>`}
function home(){const recent=data.recent.map(id=>data.items.find(i=>i.id===id)).filter(Boolean).slice(0,5);return appShell(`<main class="screen"><h1 class="title">Practice, simply.</h1><p class="subtitle">A quiet tool for progressive practice. Choose something, practise it, and let the app remember where you got to.</p><div class="menu-grid"><button class="menu-card" onclick="go('activities')"><strong>Activities</strong><span>${data.activities.length?data.activities.length+' activities':'Create your first activity'}</span></button><button class="menu-card" onclick="go('quick')"><strong>Quick Start</strong><span>Practise without setup</span></button><button class="menu-card" onclick="go('recent')"><strong>Recent</strong><span>${recent.length?'Jump back in':'Nothing yet'}</span></button><button class="menu-card" onclick="go('targets')"><strong>Targets</strong><span>${data.targets.length?data.targets.length+' targets':'Optional deadlines'}</span></button><button class="menu-card" onclick="go('settings')"><strong>Settings</strong><span>Practice &amp; data</span></button></div>${recent.length?`<section class="section"><h2>Recent</h2>${recentList(recent)}</section>`:''}</main>`)}
function recentList(items){return `<div class="list">${items.map(i=>`<button class="list-row" onclick="startPractice('${i.id}')"><div class="list-main"><strong>${esc(i.name)}</strong><small>${esc(itemSub(i))} · ${i.currentTarget} ${i.unit||'bpm'}</small></div><span class="chev">›</span></button>`).join('')}</div>`}
function itemSub(i){return [i.composer,i.piece,i.movement,i.passage].filter(Boolean).join(' · ')||i.categoryName||''}
function activities(){return appShell(`<main class="screen"><div class="backline"><button onclick="go('home')">‹ Home</button></div><h1 class="title">Activities</h1><p class="subtitle">Organise practice by skill. Each activity has its own scoring and progression rules.</p><div class="actions"><button class="btn primary" onclick="openActivityForm()">+ New activity</button></div><section class="section"><div class="list">${data.activities.length?data.activities.map(a=>`<button class="list-row" onclick="go('activity',{id:'${a.id}'})"><div class="list-main"><strong>${esc(a.name)}</strong><small>${a.music?'Music':'General'} · ${data.items.filter(i=>i.activityId===a.id).length} practice items</small></div><span class="chev">›</span></button>`).join(''):`<div class="empty">No activities yet.<br>Create one to start building your practice library.</div>`}</div></section></main>`)}
function activity(){const a=data.activities.find(x=>x.id===route.args.id);if(!a)return go('activities');if(!a.categories)a.categories=a.music?['Scales / Arpeggios','Exercises','Pieces','Random']:['General','Random'];save();const items=data.items.filter(i=>i.activityId===a.id);return appShell(`<main class="screen"><div class="backline"><button onclick="go('activities')">‹ Activities</button></div><h1 class="title">${esc(a.name)}</h1><p class="subtitle">${a.music?'Music activity':'General activity'} · ${a.scoring==='streak'?'5 in a row':'Lose 1'} · ${a.progression==='traditional'?'Traditional progression':a.progression==='single'?'Single-step progression':'Custom increments'}</p><div class="actions"><button class="btn primary" onclick="openItemForm('${a.id}')">+ Practice item</button><button class="btn" onclick="addCategory('${a.id}')">+ Category</button><button class="btn" onclick="openActivityForm('${a.id}')">Activity settings</button></div><section class="section"><h2>Categories</h2><div class="actions">${(a.categories||[]).map(c=>`<span class="pill">${esc(c)}</span>`).join('')}</div></section><section class="section"><h2>Practice items</h2>${items.length?`<div class="list">${items.map(i=>itemRow(i)).join('')}</div>`:`<div class="empty">Nothing here yet.<br>Add something you want to improve.</div>`}</section></main>`)}
function itemRow(i){return `<button class="list-row" onclick="startPractice('${i.id}')"><div class="list-main"><strong>${esc(i.name)} ${i.completed?'<span class="pill">Complete</span>':''}</strong><small>${esc(itemSub(i))} · ${i.currentTarget} ${i.unit||'bpm'}</small></div><span class="chev">›</span></button>`}
function openActivityForm(id=''){const a=data.activities.find(x=>x.id===id);modal={type:'activity',id,a};render()}
function openItemForm(activityId,id=''){const i=data.items.find(x=>x.id===id);modal={type:'item',activityId,id,i};render()}
function modalHtml(){if(!modal)return '';if(modal.type==='activity'){const a=modal.a;return `<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h2>${a?'Edit activity':'New activity'}</h2><form class="form" onsubmit="saveActivity(event)"><div class="field"><label>Name</label><input id="af-name" required value="${esc(a?.name||'')}" placeholder="Guitar"></div><div class="field"><label>Type</label><select id="af-music"><option value="1" ${a?.music!==false?'selected':''}>Music</option><option value="0" ${a?.music===false?'selected':''}>Other</option></select></div><div class="field"><label>Scoring</label><div class="seg"><button type="button" id="af-streak" class="${(a?.scoring||data.settings.defaultScoring)==='streak'?'active':''}" onclick="seg(this,'af-scoring','streak')">5 in a row</button><button type="button" id="af-minus" class="${(a?.scoring||data.settings.defaultScoring)==='minus'?'active':''}" onclick="seg(this,'af-scoring','minus')">Lose 1</button></div><input type="hidden" id="af-scoring" value="${a?.scoring||data.settings.defaultScoring}"></div><div class="field"><label>Progression</label><select id="af-progression"><option value="traditional" ${(a?.progression||data.settings.defaultProgression)==='traditional'?'selected':''}>Traditional metronome increments</option><option value="single" ${(a?.progression||data.settings.defaultProgression)==='single'?'selected':''}>Single step</option></select></div><div class="field"><label>Goal size</label><input id="af-goal" type="number" min="1" max="20" value="${a?.goal||data.settings.defaultGoal}"></div><div class="actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save</button>${a?`<button type="button" class="btn danger" onclick="deleteActivity('${a.id}')">Delete</button>`:''}</div></form></div></div>`}
const a=data.activities.find(x=>x.id===modal.activityId);const i=modal.i;return `<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h2>${i?'Edit practice item':'New practice item'}</h2><form class="form" onsubmit="saveItem(event)"><input type="hidden" id="if-activity" value="${esc(modal.activityId)}"><div class="field"><label>Name</label><input id="if-name" required value="${esc(i?.name||'')}" placeholder="La Catedral — bars 40–50"></div><div class="field"><label>Category</label><select id="if-category">${(a?.categories||['General']).map(c=>`<option ${((i?.categoryName||a?.categories?.[0])===c)?'selected':''}>${esc(c)}</option>`).join('')}</select></div>${a?.music?`<div class="inline"><div class="field"><label>Composer / artist</label><input id="if-composer" value="${esc(i?.composer||'')}" placeholder="Barrios"></div><div class="field"><label>Piece</label><input id="if-piece" value="${esc(i?.piece||'')}" placeholder="La Catedral"></div></div><div class="inline"><div class="field"><label>Movement (optional)</label><input id="if-movement" value="${esc(i?.movement||'')}"></div><div class="field"><label>Passage (optional)</label><input id="if-passage" value="${esc(i?.passage||'')}" placeholder="Bars 40–50"></div></div>`:`<div class="field"><label>What are you improving? (optional)</label><input id="if-passage" value="${esc(i?.passage||'')}" placeholder="e.g. Three-ball cascade"></div>`}<div class="inline"><div class="field"><label>Starting ${a?.music?'tempo':'goal'}</label><input id="if-start" type="number" min="1" required value="${i?.startValue||''}" placeholder="60"><button type="button" class="btn small" style="margin-top:7px" onclick="tapTempo()">Tap tempo</button></div><div class="field"><label>Ultimate target (optional)</label><input id="if-ultimate" type="number" min="1" value="${i?.ultimate??''}" placeholder="120"></div></div><div class="field"><label>Unit</label><input id="if-unit" value="${esc(i?.unit|| (a?.music?'bpm':'reps'))}" placeholder="bpm"></div><div class="field"><label>Starting point for progression</label><small style="color:var(--muted)">The first target will be the starting value. Later targets follow the activity's progression.</small></div><div class="actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">${i?'Save changes':'Create item'}</button>${i?`<button type="button" class="btn" onclick="resetItem('${i.id}')">Reset progression</button>`:''}</div></form></div></div>`}
function closeModal(){modal=null;render()}
function seg(el,id,val){el.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));el.classList.add('active');document.getElementById(id).value=val}
function saveActivity(e){e.preventDefault();const id=modal.id;const obj={id:id||uid(),name:document.getElementById('af-name').value.trim(),music:document.getElementById('af-music').value==='1',categories:modal.a?.categories||((document.getElementById('af-music').value==='1')?['Scales / Arpeggios','Exercises','Pieces','Random']:['General','Random']),scoring:document.getElementById('af-scoring').value,progression:document.getElementById('af-progression').value,goal:Math.max(1,+document.getElementById('af-goal').value||5),createdAt:modal.a?.createdAt||now()};if(!obj.name)return;if(id){Object.assign(data.activities.find(a=>a.id===id),obj)}else data.activities.push(obj);save();closeModal();go('activity',{id:obj.id})}
function addCategory(id){const a=data.activities.find(x=>x.id===id);if(!a)return;const name=prompt('Category name');if(name&&name.trim()){a.categories=a.categories||[];if(!a.categories.includes(name.trim()))a.categories.push(name.trim());save();render()}}
function deleteActivity(id){if(!confirm('Delete this activity and its practice items?'))return;data.activities=data.activities.filter(a=>a.id!==id);data.items=data.items.filter(i=>i.activityId!==id);data.recent=data.recent.filter(x=>data.items.some(i=>i.id===x));save();closeModal();go('activities')}
function saveItem(e){e.preventDefault();const id=modal.id,a=data.activities.find(x=>x.id===modal.activityId);const start=Math.max(1,+document.getElementById('if-start').value||1);const existing=modal.i;const obj={id:id||uid(),activityId:a.id,name:document.getElementById('if-name').value.trim(),categoryName:document.getElementById('if-category').value,composer:document.getElementById('if-composer')?.value.trim()||'',piece:document.getElementById('if-piece')?.value.trim()||'',movement:document.getElementById('if-movement')?.value.trim()||'',passage:document.getElementById('if-passage')?.value.trim()||'',startValue:existing?.startValue||start,ultimate:document.getElementById('if-ultimate').value?Math.max(1,+document.getElementById('if-ultimate').value):null,unit:document.getElementById('if-unit').value.trim()||'bpm',currentTarget:existing?.currentTarget??start,lastCompleted:existing?.lastCompleted??null,completed:existing?.completed||false,createdAt:existing?.createdAt||now(),updatedAt:now()};if(!obj.name)return;if(id)Object.assign(data.items.find(i=>i.id===id),obj);else data.items.push(obj);save();closeModal();go('activity',{id:a.id})}
function resetItem(id){const i=data.items.find(x=>x.id===id);if(!i)return;if(confirm('Reset this item to its starting target?')){i.currentTarget=i.startValue;i.lastCompleted=null;i.completed=false;i.updatedAt=now();save();closeModal();go('activity',{id:i.activityId})}}
let metroTimer=null,metroCtx=null,metroBeat=0;
function startMetronome(){if(!data.settings.metronome)return;if(!metroCtx)metroCtx=new (window.AudioContext||window.webkitAudioContext)();if(metroCtx.state==='suspended')metroCtx.resume();stopMetronome();const i=data.items.find(x=>x.id===route.args.id);if(!i)return;const bpm=i.currentTarget;const interval=60000/bpm;metroBeat=0;const tick=()=>{if(!metroCtx)return;const o=metroCtx.createOscillator(),g=metroCtx.createGain();o.frequency.value=900;g.gain.setValueAtTime(.035,metroCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,metroCtx.currentTime+.045);o.connect(g).connect(metroCtx.destination);o.start();o.stop(metroCtx.currentTime+.05);metroBeat++};tick();metroTimer=setInterval(tick,interval)}
function stopMetronome(){if(metroTimer){clearInterval(metroTimer);metroTimer=null}}
function restartMetronome(){if(route.name==='practice'&&data.settings.metronome)startMetronome()}
function tapTempo(){const nowt=performance.now();window._taps=window._taps||[];window._taps=window._taps.filter(t=>nowt-t<3000);window._taps.push(nowt);if(window._taps.length>=2){const gaps=[];for(let j=1;j<window._taps.length;j++)gaps.push(window._taps[j]-window._taps[j-1]);const bpm=Math.round(60000/(gaps.reduce((x,y)=>x+y,0)/gaps.length));document.getElementById('if-start').value=Math.max(20,Math.min(300,bpm));}}
function startPractice(id){const i=data.items.find(x=>x.id===id);if(!i)return;data.recent=[id,...data.recent.filter(x=>x!==id)].slice(0,5);save();practiceState={id,score:0,dragX:0,startX:0};route={name:'practice',args:{id}};render()}
function nextTempo(v,mode){if(mode==='single')return v+1;let idx=DEFAULT_TEMPOS.findIndex(x=>x>v);return idx<0?v+8:DEFAULT_TEMPOS[idx]}
function practice(){const i=data.items.find(x=>x.id===route.args.id),a=i&&data.activities.find(x=>x.id===i.activityId);if(!i||!a)return go('home');if(!practiceState||practiceState.id!==i.id)practiceState={id:i.id,score:0};return `<div class="app"><div class="topbar"><button class="icon-btn" onclick="leavePractice()" aria-label="Home">⌂</button><div class="brand">Practice</div><button class="icon-btn" onclick="openPracticeSettings()" aria-label="Settings">⚙</button></div><main class="practice"><div class="practice-head"><div class="meta">${esc(i.composer||'')}</div><h1>${esc(i.piece||i.name)}</h1><div class="passage">${esc(i.passage||i.movement|| (i.piece?i.name:''))}</div></div><div class="tempo-row"><button class="round" onclick="adjustTempo(-1)">−</button><div class="tempo">${i.currentTarget} <small style="font-size:15px;color:var(--muted);letter-spacing:0">${esc(i.unit||'bpm')}</small></div><button class="round" onclick="adjustTempo(1)">+</button></div><div class="pebbles">${Array.from({length:i.goal||a.goal||5},(_,n)=>`<div class="pebble ${n<practiceState.score?'done':''}"></div>`).join('')}</div><div id="swipeZone" class="swipe-zone"><div class="hint">Swipe right for a perfect attempt<br>Swipe left if it wasn't</div></div><div class="practice-controls"><button class="btn small" onclick="openPracticeSettings()">${a.scoring==='streak'?'5 in a row':'Lose 1'}</button><span class="tiny">${i.lastCompleted?`Last: ${i.lastCompleted} ${i.unit||'bpm'}`:'Not yet completed'}</span><button class="btn small" onclick="leavePractice()">Home</button></div></main></div>`}
function leavePractice(){practiceState=null;stopMetronome();go('home')}
function adjustTempo(d){const i=data.items.find(x=>x.id===route.args.id);if(!i)return;i.currentTarget=Math.max(1,i.currentTarget+d);i.updatedAt=now();save();render()}
function attempt(success){const i=data.items.find(x=>x.id===route.args.id),a=data.activities.find(x=>x.id===i.activityId);if(!i)return;const goal=i.goal||a.goal||5;if(success)practiceState.score=Math.min(goal,practiceState.score+1);else practiceState.score=a.scoring==='streak'?0:Math.max(0,practiceState.score-1);if(practiceState.score>=goal){const achieved=i.currentTarget;i.lastCompleted=achieved;const next=nextTempo(achieved,a.progression);if(i.ultimate&&achieved>=i.ultimate){i.completed=true;i.updatedAt=now();save();celebrate('Complete');setTimeout(()=>{practiceState=null;go('activity',{id:a.id})},700);return}i.currentTarget=next;i.updatedAt=now();practiceState.score=0;save();render();celebrate(`${achieved} ${i.unit||'bpm'}`)}else{save();render()}}
function celebrate(t){const d=document.createElement('div');d.className='celebrate';d.innerHTML=`<span>✓ ${esc(t)}</span>`;document.body.appendChild(d);setTimeout(()=>d.remove(),850)}
function bindSwipe(){const z=document.getElementById('swipeZone');if(!z)return;let sx=0,sy=0;z.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;z.setPointerCapture?.(e.pointerId)});z.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.2)attempt(dx>0)})}
function openPracticeSettings(){modal={type:'practiceSettings'};render()}
function settings(){return appShell(`<main class="screen"><div class="backline"><button onclick="go('home')">‹ Home</button></div><h1 class="title">Settings</h1><p class="subtitle">Keep the defaults simple. Activity settings can override these for individual activities.</p><div class="card"><div class="setting-row"><div><strong>Default scoring</strong><small>Used when creating new activities.</small></div><div class="seg"><button class="${data.settings.defaultScoring==='streak'?'active':''}" onclick="setSetting('defaultScoring','streak')">5 in a row</button><button class="${data.settings.defaultScoring==='minus'?'active':''}" onclick="setSetting('defaultScoring','minus')">Lose 1</button></div></div><div class="setting-row"><div><strong>Default progression</strong><small>Used for new activities.</small></div><div class="seg"><button class="${data.settings.defaultProgression==='traditional'?'active':''}" onclick="setSetting('defaultProgression','traditional')">Traditional</button><button class="${data.settings.defaultProgression==='single'?'active':''}" onclick="setSetting('defaultProgression','single')">Single</button></div></div><div class="setting-row"><div><strong>Metronome</strong><small>Audible metronome preference.</small></div><button class="btn small" onclick="setSetting('metronome',${!data.settings.metronome})">${data.settings.metronome?'On':'Off'}</button></div></div><section class="section"><h2>Data</h2><div class="actions"><button class="btn" onclick="exportData()">Export data</button><button class="btn" onclick="document.getElementById('importFile').click()">Import data</button><input id="importFile" type="file" accept="application/json" hidden onchange="importData(event)"><button class="btn danger" onclick="clearData()">Delete all data</button></div><p class="danger-note">Your data is stored locally in this browser. Export a backup if you want to move it or keep a copy.</p></section></main>`)}
function practiceSettings(){const i=data.items.find(x=>x.id===route.args.id),a=data.activities.find(x=>x.id===i.activityId);return `<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h2>Practice settings</h2><div class="setting-row"><div><strong>Scoring</strong><small>Set by this activity.</small></div><span class="pill">${a.scoring==='streak'?'5 in a row':'Lose 1'}</span></div><div class="setting-row"><div><strong>Goal</strong><small>Successful attempts needed.</small></div><div class="actions"><button class="btn small" onclick="changeGoal('${i.id}',-1)">−</button><span style="padding:9px">${i.goal||a.goal||5}</span><button class="btn small" onclick="changeGoal('${i.id}',1)">+</button></div></div><div class="setting-row"><div><strong>Metronome</strong><small>Audible click follows the current target tempo.</small></div><button class="btn small" onclick="toggleMetronome()">${data.settings.metronome?'On':'Off'}</button></div><div class="setting-row"><div><strong>Time signature</strong><small>No accent by default.</small></div><select onchange="setSetting('timeSignature',this.value)"><option value="none" ${data.settings.timeSignature==='none'?'selected':''}>No accent</option><option value="2" ${data.settings.timeSignature==='2'?'selected':''}>2/4</option><option value="3" ${data.settings.timeSignature==='3'?'selected':''}>3/4</option><option value="4" ${data.settings.timeSignature==='4'?'selected':''}>4/4</option><option value="6" ${data.settings.timeSignature==='6'?'selected':''}>6/8</option></select></div><div class="actions" style="margin-top:16px"><button class="btn" onclick="closeModal()">Close</button><button class="btn" onclick="editCurrentItem()">Edit item</button></div></div></div>`}
function changeGoal(id,d){const i=data.items.find(x=>x.id===id),a=data.activities.find(x=>x.id===i.activityId);i.goal=Math.max(1,Math.min(20,(i.goal||a.goal||5)+d));practiceState.score=0;save();render()}
function toggleMetronome(){data.settings.metronome=!data.settings.metronome;save();render()}
function editCurrentItem(){const i=data.items.find(x=>x.id===route.args.id);closeModal();openItemForm(i.activityId,i.id)}
function setSetting(k,v){data.settings[k]=v;save();render()}
function recent(){const items=data.recent.map(id=>data.items.find(i=>i.id===id)).filter(Boolean);return appShell(`<main class="screen"><div class="backline"><button onclick="go('home')">‹ Home</button></div><h1 class="title">Recent</h1><p class="subtitle">Jump straight back into the five things you've worked on most recently.</p>${items.length?recentList(items):'<div class="empty">Nothing here yet. Start practising and your recent items will appear here.</div>'}</main>`)}
function targets(){return appShell(`<main class="screen"><div class="backline"><button onclick="go('home')">‹ Home</button></div><h1 class="title">Targets</h1><p class="subtitle">Optional deadlines for things you want to achieve.</p><div class="actions"><button class="btn primary" onclick="openTargetForm()">+ New target</button></div><section class="section"><div class="list">${data.targets.length?data.targets.map(t=>{const i=data.items.find(x=>x.id===t.itemId);return `<div class="list-row"><div class="list-main"><strong>${esc(i?.name||'Deleted item')}</strong><small>${t.value} ${esc(i?.unit||'bpm')} · ${t.deadline?new Date(t.deadline).toLocaleDateString('en-GB'):'No deadline'} ${t.done?'<span class="pill">Complete</span>':''}</small></div><button class="btn small" onclick="deleteTarget('${t.id}')">×</button></div>`}).join(''):`<div class="empty">No targets yet.</div>`}</div></section></main>`)}
function openTargetForm(){modal={type:'target'};render()}
function targetModal(){const eligible=data.items.filter(i=>!i.completed);return `<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h2>New target</h2><form class="form" onsubmit="saveTarget(event)"><div class="field"><label>Practice item</label><select id="tf-item" required>${eligible.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('')}</select></div><div class="inline"><div class="field"><label>Target</label><input id="tf-value" type="number" min="1" required></div><div class="field"><label>Deadline (optional)</label><input id="tf-date" type="date"></div></div><div class="actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save</button></div></form></div></div>`}
function saveTarget(e){e.preventDefault();data.targets.push({id:uid(),itemId:document.getElementById('tf-item').value,value:+document.getElementById('tf-value').value,deadline:document.getElementById('tf-date').value||null,done:false});save();closeModal();go('targets')}
function deleteTarget(id){data.targets=data.targets.filter(t=>t.id!==id);save();render()}
function quick(){return appShell(`<main class="screen"><div class="backline"><button onclick="go('home')">‹ Home</button></div><h1 class="title">Quick Start</h1><p class="subtitle">Start practising immediately. No activity or practice item required.</p><form class="form card" onsubmit="startQuick(event)"><div class="field"><label>What are you practising?</label><input id="q-name" required placeholder="e.g. Mill's Mess"></div><div class="field"><label>Optional goal / target</label><input id="q-goal" type="number" min="1" placeholder="e.g. 25"></div><div class="field"><label>Unit (optional)</label><input id="q-unit" placeholder="catches, serves, reps..."></div><div class="actions"><button class="btn primary">Start</button></div></form></main>`)}
let quickState=null;
function startQuick(e){e.preventDefault();quickState={name:document.getElementById('q-name').value.trim(),goal:+document.getElementById('q-goal').value||null,unit:document.getElementById('q-unit').value.trim()||'',attempts:0,successes:0,score:0};route={name:'quickPractice'};render()}
function quickPractice(){return `<div class="app"><div class="topbar"><button class="icon-btn" onclick="stopQuick()">⌂</button><div class="brand">Quick Start</div><div></div></div><main class="practice"><div class="practice-head"><h1>${esc(quickState.name)}</h1>${quickState.goal?`<div class="passage">Target: ${quickState.goal} ${esc(quickState.unit)}</div>`:''}</div><div class="pebbles">${Array.from({length:5},(_,n)=>`<div class="pebble ${n<quickState.score?'done':''}"></div>`).join('')}</div><div id="quickZone" class="swipe-zone"><div class="hint">Swipe right for success<br>Swipe left for unsuccessful attempt</div></div><div class="practice-controls"><span class="tiny">${quickState.attempts} attempts · ${quickState.successes} successes</span><button class="btn small" onclick="stopQuick()">Stop</button></div></main></div>`}
function quickAttempt(success){quickState.attempts++;if(success){quickState.successes++;quickState.score=Math.min(5,quickState.score+1)}else quickState.score= data.settings.defaultScoring==='streak'?0:Math.max(0,quickState.score-1);if(quickState.score===5){quickState.score=0;celebrate('✓ 5');}render()}
function stopQuick(){if(!quickState)return;route={name:'quickSummary'};render()}
function quickSummary(){const q=quickState,p=q.attempts?Math.round(q.successes/q.attempts*100):0;return appShell(`<main class="screen"><h1 class="title">Session complete</h1><p class="subtitle">${esc(q.name)}</p><div class="card"><div class="setting-row"><strong>Attempts</strong><span>${q.attempts}</span></div><div class="setting-row"><strong>Successes</strong><span>${q.successes}</span></div><div class="setting-row"><strong>Success rate</strong><span>${p}%</span></div></div><div class="actions" style="margin-top:18px"><button class="btn primary" onclick="openQuickSave()">Save as practice item</button><button class="btn" onclick="quickState=null;go('home')">Done</button></div></main>`)}
function openQuickSave(){modal={type:'quickSave'};render()}
function quickSaveModal(){return `<div class="modal"><div class="sheet"><h2>Save practice item</h2><form class="form" onsubmit="saveQuickItem(event)"><div class="field"><label>Activity</label><select id="qs-a" required>${data.activities.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>Category</label><input id="qs-c" placeholder="e.g. Three-ball tricks"></div><div class="field"><label>Starting target</label><input id="qs-start" type="number" min="1" placeholder="e.g. 25"></div><div class="actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save</button></div></form></div></div>`}
function saveQuickItem(e){e.preventDefault();const a=data.activities.find(x=>x.id===document.getElementById('qs-a').value);const q=quickState;const start=+document.getElementById('qs-start').value||q.goal||1;data.items.push({id:uid(),activityId:a.id,name:q.name,categoryName:document.getElementById('qs-c').value.trim(),passage:q.unit,startValue:start,currentTarget:start,lastCompleted:null,ultimate:null,unit:q.unit||'reps',completed:false,createdAt:now(),updatedAt:now()});save();quickState=null;closeModal();go('activity',{id:a.id})}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='practice-app-backup.json';a.click();URL.revokeObjectURL(url)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.activities||!d.items)throw Error();data=d;save();render();toast('Data imported')}catch{alert('That file does not look like a Practice App backup.')}};r.readAsText(f)}
function clearData(){if(confirm('Delete all Practice App data from this browser? This cannot be undone.')){localStorage.removeItem(KEY);data=load();go('home')}}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function render(){let html='';if(route.name==='home')html=home();else if(route.name==='activities')html=activities();else if(route.name==='activity')html=activity();else if(route.name==='practice')html=practice();else if(route.name==='recent')html=recent();else if(route.name==='targets')html=targets();else if(route.name==='settings')html=settings();else if(route.name==='quick')html=quick();else if(route.name==='quickPractice')html=quickPractice();else if(route.name==='quickSummary')html=quickSummary();document.getElementById('app').innerHTML=html+(modal?modalHtmlFor(): '');if(route.name==='practice'){bindSwipe();if(data.settings.metronome)startMetronome()}if(route.name==='quickPractice')bindQuickSwipe()}
function modalHtmlFor(){if(modal.type==='practiceSettings')return practiceSettings();if(modal.type==='target')return targetModal();if(modal.type==='quickSave')return quickSaveModal();return modalHtml()}
function bindQuickSwipe(){const z=document.getElementById('quickZone');if(!z)return;let sx=0,sy=0;z.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY});z.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.2)quickAttempt(dx>0)})}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
